### PR TITLE
fix: Only update .gitignore when a link is indeed created

### PR DESCRIPTION
**Pull request by Atry**
It does not make sense to update `.gitignore` if there is an existing manually created file

### CODE REVIEW

**Comment by Atry** [comment]
Could you review this PR, please? @blaggacao

**Review by blaggacao — APPROVED** [review]
LGTM, thanks for the catch! cc/ @jmgilman

**Comment by Atry** [comment]
Any blocker to merge this PR?

**Review by blaggacao — APPROVED** [review]

**Comment by Atry** [comment]
It seems that you approved this pull request twice

**Comment by Atry** [comment]
@blaggacao  Could you merge this PR, please?

**Review by blaggacao — APPROVED** [review]
Lgtm @jmgilman could you merge?

**Comment by Atry** [comment]
Is this project still actively maintained by @jmgilman?

If no, @blaggacao do you want to maintain this project?

**Comment by blaggacao** [comment]
Yeah, based on the knowledge of the codebase and downstream dependencies that I co-maintain, I could take maintainership, if desired.

**Comment by Atry** [comment]
Thank you! 

Do you want to create a post to request the permission here: https://github.com/orgs/nix-community/discussions

**Comment by jmgilman** [comment]
I'd be happy to transfer maintainership to @blaggacao. We no longer utilize this in our stack so it will be hard for me to keep up with it.

**Pull request merged**
